build:
  stage: build
  # before_script:
  script: 
    - rm -rf build
    - python3 genmake.py
    - make all config=debug
    - make all config=release

test:
  stage: test
  script:
    - ./utest.sh "*" debug
    - ./utest.sh "*" release
