build:
  stage: build
  # before_script:
  script: 
    - rm -rf build
    - python3 genmake.py
    - make all config=debug
    - make all config=release

test:
  stage: test
  script:
    - ./utest.sh "*" debug
    - ./utest.sh "*" release
    - ./valgrind.sh "*" debug 
    - ./valgrind.sh "*" release
    - ./coverage.sh
  coverage: '/^  lines\.\.\.\.\.\.: (\d+\.\d*%)/'
  artifacts:
    paths:
      - covhtml/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv covhtml/ public/
  artifacts:
    paths:
      - public
  only:
    - master
